#!/usr/bin/env python3
"""Generate the compact WHO daily percentile data module from official XLSX files.

This is a maintainer-only script. The application imports the generated TypeScript
module and does not need Python, openpyxl, or network access at runtime.
"""

from __future__ import annotations

import argparse
import base64
import struct
from decimal import Decimal, ROUND_HALF_UP
from pathlib import Path

import openpyxl


MAX_DAY = 1856
PERCENTILES = ("P3", "P15", "P50", "P85", "P97")
SOURCES = {
    ("male", "weightKg"): ("wfa-boys-percentiles-expanded-tables.xlsx", "daily-wfa-boys.xlsx"),
    ("male", "heightCm"): ("lhfa-boys-percentiles-expanded-tables.xlsx", "daily-lhfa-boys.xlsx"),
    ("male", "headCircumferenceCm"): ("hcfa-boys-percentiles-expanded-tables.xlsx", "daily-hcfa-boys.xlsx"),
    ("female", "weightKg"): ("wfa-girls-percentiles-expanded-tables.xlsx", "daily-wfa-girls.xlsx"),
    ("female", "heightCm"): ("lhfa-girls-percentiles-expanded-tables.xlsx", "daily-lhfa-girls.xlsx"),
    ("female", "headCircumferenceCm"): ("hcfa-girls-percentiles-expanded-tables.xlsx", "daily-hcfa-girls.xlsx"),
}


def scaled(value: object) -> int:
    return int((Decimal(str(value)) * 1000).to_integral_value(rounding=ROUND_HALF_UP))


def read_rows(path: Path) -> list[tuple[int, int, int, int, int]]:
    workbook = openpyxl.load_workbook(path, read_only=True, data_only=True)
    sheet = workbook.active
    rows = sheet.iter_rows(values_only=True)
    header = next(rows)
    columns = {str(name): index for index, name in enumerate(header)}
    age_column = columns.get("Age", columns.get("Day"))
    if age_column is None or any(name not in columns for name in PERCENTILES):
        raise ValueError(f"{path.name}: unsupported header")

    result: list[tuple[int, int, int, int, int]] = []
    for expected_day, row in enumerate(rows):
        day = int(row[age_column])
        if day != expected_day:
            raise ValueError(f"{path.name}: expected day {expected_day}, got {day}")
        result.append(tuple(scaled(row[columns[name]]) for name in PERCENTILES))
    if len(result) != MAX_DAY + 1:
        raise ValueError(f"{path.name}: expected {MAX_DAY + 1} rows, got {len(result)}")
    return result


def encode(rows: list[tuple[int, int, int, int, int]]) -> str:
    payload = bytearray(struct.pack("<5I", *rows[0]))
    for previous, current in zip(rows, rows[1:]):
        deltas = tuple(value - old for old, value in zip(previous, current))
        if any(delta < -32768 or delta > 32767 for delta in deltas):
            raise ValueError(f"daily delta does not fit int16: {deltas}")
        payload.extend(struct.pack("<5h", *deltas))
    return base64.b64encode(payload).decode("ascii")


def render(data: dict[tuple[str, str], str]) -> str:
    lines = [
        "// Generated by scripts/generate-who-growth-standards.py.",
        "// Do not edit by hand. Source provenance: docs/who-growth-standards.md", 
        "",
        "export const WHO_GROWTH_DATA_ENCODED = {",
    ]
    for sex in ("male", "female"):
        lines.append(f"  {sex}: {{")
        for metric in ("weightKg", "heightCm", "headCircumferenceCm"):
            lines.append(f'    {metric}: "{data[(sex, metric)]}",')
        lines.append("  },")
    lines.extend(["} as const;", ""])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source-dir", type=Path, required=True)
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(__file__).resolve().parents[1] / "lib" / "who-growth-data.generated.ts",
    )
    args = parser.parse_args()
    data = {}
    for key, filenames in SOURCES.items():
        source = next((args.source_dir / filename for filename in filenames if (args.source_dir / filename).is_file()), None)
        if source is None:
            raise FileNotFoundError(f"missing WHO source file: {filenames[0]}")
        data[key] = encode(read_rows(source))
    args.output.write_text(render(data), encoding="utf-8")


if __name__ == "__main__":
    main()
